stages:
  	- build
  	- deploy
  	- test

variables:
  	RAILS_ENV: "test"
  	NODE_ENV: "test"
  	GIT_STRATEGY: "clone"
  	CHROME_VERSION: "103"
  	DOCKER_VERSION: "20.10.14"

build-job:
 	 stage: build
 	 script:
 	   - echo "Checking node version and building docker image..."
 	   - node -v
 	   - bash build.sh

deploy-code:
	  stage: deploy
	  needs: build-job
	  script:
	    - echo "Deploying code..."
	    - cd ./backend/desired/folder
	    - bash deploy.sh

test-code:
	  stage: test
	  needs: deploy-code
	  script:
	    - echo "Running tests..."
	    - cd to/your/desired/folder
	    - npm run test