stages:
  	- build
  	- deploy
  	- test

variables:
  	NODE_ENV: "test"
  	GIT_STRATEGY: "clone"
  	CHROME_VERSION: "103"
  	DOCKER_VERSION: "20.10.14"

build-job:
 	 stage: build
 	 script:
 	   - echo "Checking node version and building docker image..."
 	   - node -v
 	   - bash build.sh

deploy-frontend:
	  stage: deploy
	  needs: build-job
	  script:
	    - echo "Deploying frontend..."
	    - cd ./backend
	    - bash deployBackend.sh

deploy-backend:
	  stage: deploy
	  needs: build-job
	  script:
	    - echo "Deploying backend..."
	    - cd ./frontend
	    - bash deployFrontend.sh

test-code:
	  stage: test
	  needs: deploy-code
	  script:
	    - echo "Running frontend tests..."
	    - cd ./frontend
	    - npm test